services:
  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      TZ: Europe/Istanbul
      IS_DOCKER: "true"
    env_file:
      - .env
    depends_on:
      - redis

  celery-worker:
    build: .
    command: celery -A config worker --loglevel=info --concurrency=4
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      TZ: Europe/Istanbul
      IS_DOCKER: "true"
    env_file:
      - .env
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      TZ: Europe/Istanbul
      IS_DOCKER: "true"
    env_file:
      - .env
    depends_on:
      - redis
      - web

volumes:
  redis_data:
  static_volume:
  media_volume: