# Generated by Django 5.2.6 on 2025-09-26 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('task_stats', models.JSONField(default=dict)),
                ('productivity_score', models.FloatField(default=0)),
                ('weekly_trends', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Analytics',
                'indexes': [models.Index(fields=['user', 'last_updated'], name='analytics_u_user_id_d4f855_idx')],
            },
        ),
    ]
