# Generated by Django 5.2.6 on 2025-10-02 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['productivity_score'], name='analytics_u_product_77ede4_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['last_updated'], name='analytics_u_last_up_08e121_idx'),
        ),
    ]
