# Generated by Django 5.2.6 on 2025-09-26 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('reminder', 'Hatırlatıcı'), ('event', 'Etkinlik'), ('note', 'Not'), ('task', 'Görev')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('reminder', models.PositiveIntegerField(blank=True, choices=[(5, '5 dakika önce'), (15, '15 dakika önce'), (30, '30 dakika önce'), (60, '1 saat önce'), (1440, '1 gün önce')], null=True, verbose_name='Hatırlatıcı')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Hatırlatıcı Gönderildi')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('pomodoros_completed', models.PositiveIntegerField(default=0)),
                ('notes_created', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
