# Generated by Django 5.2.6 on 2025-10-01 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_pomodorosession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pomodorosession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pomodoro Oturumu', 'verbose_name_plural': 'Pomodoro Oturumları'},
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='duration',
            field=models.IntegerField(default=25, help_text='Dakika cinsinden'),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='session_type',
            field=models.CharField(choices=[('work', 'Çalışma'), ('break', 'Mola')], default='work', max_length=10),
        ),
        migrations.AlterField(
            model_name='pomodorosession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
