# Generated by Django 5.2.6 on 2025-10-02 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_pomodorosession_options_and_more'),
        ('notes', '0002_category_notes_categ_user_id_f7e623_idx_and_more'),
        ('todo', '0002_category_todo_catego_user_id_fb6e6b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'start_date'], name='dashboard_c_user_id_040dec_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['start_date', 'end_date'], name='dashboard_c_start_d_2911ef_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='dashboard_c_event_t_cdd041_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'event_type', 'start_date'], name='dashboard_c_user_id_8f793e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstats',
            index=models.Index(fields=['user', 'last_updated'], name='dashboard_d_user_id_668f95_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstats',
            index=models.Index(fields=['current_streak'], name='dashboard_d_current_f6a1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardstats',
            index=models.Index(fields=['last_updated'], name='dashboard_d_last_up_1c2d31_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'created_at'], name='dashboard_p_user_id_c2ae1e_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['session_type'], name='dashboard_p_session_a85758_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['completed'], name='dashboard_p_complet_f16a01_idx'),
        ),
        migrations.AddIndex(
            model_name='pomodorosession',
            index=models.Index(fields=['user', 'session_type', 'created_at'], name='dashboard_p_user_id_c985ec_idx'),
        ),
    ]
