# Generated by Django 5.2.6 on 2025-10-02 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('todo', '0002_category_todo_catego_user_id_fb6e6b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='notes_categ_user_id_f7e623_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='notes_categ_slug_309fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'created_at'], name='notes_note_user_id_59cb89_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'updated_at'], name='notes_note_user_id_630db2_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_pinned'], name='notes_note_is_pinn_2c469e_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['priority'], name='notes_note_priorit_065697_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'category'], name='notes_note_user_id_850a77_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'task'], name='notes_note_user_id_c03259_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_pinned', 'updated_at'], name='notes_note_user_id_b997af_idx'),
        ),
    ]
