# Generated by Django 5.2.4 on 2025-08-18 09:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rozet Tipi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('color', models.CharField(default='#6c757d', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('icon', models.CharField(default='fas fa-medal', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Rozet Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('criteria', models.JSONField(default=dict, help_text='Kazanma kriterleri (JSON formatında)')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('is_secret', models.BooleanField(default=False, verbose_name='Gizli Rozet')),
                ('icon', models.CharField(default='fas fa-medal', max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('badge_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='user_profile.badgetype')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('task', 'Görev'), ('note', 'Not'), ('system', 'Sistem'), ('achievement', 'Başarı')], max_length=20)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Hakkımda')),
                ('profile_picture', models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/', verbose_name='Profil Resmi')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Konum')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('pomodoro_duration', models.PositiveIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='Pomodoro Süresi (dakika)')),
                ('daily_goal', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Günlük Hedef (görev)')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Anlık Bildirimler')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='Bildirim Sesi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Görüldü mü?')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='user_profile.badge')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='user_profile.profile')),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('user_profile', 'badge')},
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(related_name='profiles', through='user_profile.UserBadge', to='user_profile.badge'),
        ),
    ]
