# Generated by Django 5.2.6 on 2025-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Rozet', 'verbose_name_plural': 'Rozetler'},
        ),
        migrations.AlterModelOptions(
            name='badgetype',
            options={'verbose_name': 'Rozet Tipi', 'verbose_name_plural': 'Rozet Tipleri'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Kullanıcı Rozeti', 'verbose_name_plural': 'Kullanıcı Rozetleri'},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Giriş Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_pomodoro_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Pomodoro Tarihi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='Giriş Serisi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_pomodoro_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Pomodoro Süresi (dakika)'),
        ),
    ]
