# Generated by Django 5.2.6 on 2025-10-02 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_badge_options_alter_badgetype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['name'], name='user_profil_name_e40297_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['slug'], name='user_profil_slug_2c2e38_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['badge_type'], name='user_profil_badge_t_2c35ac_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['is_secret'], name='user_profil_is_secr_131bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='badgetype',
            index=models.Index(fields=['name'], name='user_profil_name_c1e8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='user_profil_user_id_ad73b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='user_profil_user_id_38d499_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='user_profil_created_cb6650_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='user_profil_is_read_103f85_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='user_profil_notific_4a9fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='user_profil_user_id_31e609_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['slug'], name='user_profil_slug_37b871_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['login_streak'], name='user_profil_login_s_bce78b_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user_profile', 'awarded_at'], name='user_profil_user_pr_7cb590_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['awarded_at'], name='user_profil_awarded_5d58df_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['is_seen'], name='user_profil_is_seen_d09d09_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user_profile', 'is_seen'], name='user_profil_user_pr_67b292_idx'),
        ),
    ]
