# Generated by Django 5.2.6 on 2025-10-03 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Liste Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('list_type', models.CharField(choices=[('shopping', '🛒 Alışveriş Listesi'), ('todo', '✅ Yapılacaklar Listesi'), ('work', '💼 İş Listesi'), ('personal', '🎯 Kişisel Liste'), ('custom', '📝 Özel Liste')], default='custom', max_length=20, verbose_name='Liste Türü')),
                ('color', models.CharField(default='#FFD700', max_length=7, verbose_name='Renk Kodu')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Sabitlenmiş')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Madde İçeriği')),
                ('completed', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('priority', models.CharField(choices=[('low', '🔽 Düşük'), ('medium', '🔼 Orta'), ('high', '⏫ Yüksek'), ('urgent', '🚨 Acil')], default='medium', max_length=10, verbose_name='Öncelik')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Tarih')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lists.list')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', 'created_at'], name='lists_list_user_id_291c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', 'list_type'], name='lists_list_user_id_742bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'completed'], name='lists_listi_list_id_375c47_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'priority'], name='lists_listi_list_id_187cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['due_date'], name='lists_listi_due_dat_f4cf7b_idx'),
        ),
    ]
