# Generated by Django 5.2.6 on 2025-09-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studynote',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
    ]
